name: Extract Text from Quix Docs
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for hello world data
    defaultValue: raw-documents-html
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
